// Generated by CoffeeScript 1.7.1
var Admin, PGConnect, TYPE, config, debug, filter, getForEmail, globals, isAdmin, settings, user, verifyCredentials,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

user = require('./user');

globals = require('../globals');

debug = globals.debug;

config = globals.config;

PGConnect = globals.PGConnect;

settings = require('../settings');

TYPE = 'Admin';

Admin = (function(_super) {
  __extends(Admin, _super);

  function Admin(email, name) {
    this.email = email;
    this.name = name;
    this.type = TYPE;
  }

  return Admin;

})(user.User);

verifyCredentials = function(email, password, callback) {
  if (email === config.admin.email) {
    return settings.get('admin_pass', function(err, validPassword) {
      return typeof callback === "function" ? callback(null, password === validPassword) : void 0;
    });
  } else {
    return process.nextTick(function() {
      return typeof callback === "function" ? callback(null, false) : void 0;
    });
  }
};

isAdmin = function(email, callback) {
  return process.nextTick(function() {
    return typeof callback === "function" ? callback(null, email === config.admin.email) : void 0;
  });
};

getForEmail = function(email, callback) {
  if (email === config.admin.email) {
    return process.nextTick(function() {
      return typeof callback === "function" ? callback(null, new Admin(config.admin.email, config.admin.name)) : void 0;
    });
  } else {
    return process.nextTick(function() {
      return typeof callback === "function" ? callback(null, null) : void 0;
    });
  }
};

filter = function(req, res, next) {
  debug("Admin Auth Filter: " + req.url);
  if (!req.session.user) {
    return res.redirect("/auth/signin?redirect=" + (encodeURIComponent(req.url)));
  }
  isAdmin(req.session.user.email, function(err, adminValidity) {
    if (!adminValidity) {
      if (req.session.user) {
        if (req.session.user.type === TYPE) {
          req.session.user = null;
          return res.redirect("/auth/signin");
        } else {
          return res.redirect("/dashboard");
        }
      } else {
        req.url = "/auth/signin/admin";
      }
    }
    return next();
  });
};

module.exports = {
  Admin: Admin,
  type: TYPE,
  filter: filter,
  verifyCredentials: verifyCredentials,
  isAdmin: isAdmin,
  getForEmail: getForEmail
};
