// Generated by CoffeeScript 1.7.1
var PGConnect, config, configConvict, pg;

pg = require('pg');

configConvict = require('./config');

configConvict.validate();

config = configConvict.get();

PGConnect = function(callback) {
  return pg.connect(config.pg_url, callback);
};

module.exports = {
  config: config,
  debug: require('debug')('app'),
  PGConnect: PGConnect
};
