// Generated by CoffeeScript 1.7.1
var EntityName, PGConnect, globals;

globals = require('./globals');

PGConnect = globals.PGConnect;

EntityName = '"public"."Setting"';

module.exports = {
  get: function(key, callback) {
    return PGConnect(function(err, client, done) {
      if (err) {
        if (typeof done === "function") {
          done(client);
        }
        if (typeof callback === "function") {
          callback(err);
        }
        return;
      }
      return client.query({
        name: "setting_get",
        text: "SELECT value FROM " + EntityName + " WHERE key = $1::varchar ",
        values: [key]
      }, function(err, result) {
        if (err) {
          if (typeof done === "function") {
            done(client);
          }
          if (typeof callback === "function") {
            callback(err);
          }
          return;
        }
        if (typeof done === "function") {
          done();
        }
        return typeof callback === "function" ? callback(null, result.rows[0] ? result.rows[0].value : null) : void 0;
      });
    });
  },
  set: function(key, value, callback) {
    return PGConnect(function(err, client, done) {
      if (err) {
        if (typeof done === "function") {
          done(client);
        }
        if (typeof callback === "function") {
          callback(err);
        }
        return;
      }
      return client.query({
        name: "setting_set",
        text: "UPDATE " + EntityName + " SET value=$2::varchar where key=$1::varchar ",
        values: [key, value]
      }, function(err, result) {
        if (err) {
          if (typeof done === "function") {
            done(client);
          }
          if (typeof callback === "function") {
            callback(err);
          }
          return;
        }
        if (typeof done === "function") {
          done();
        }
        return typeof callback === "function" ? callback() : void 0;
      });
    });
  }
};
