// Generated by CoffeeScript 1.7.1
var PGConnect, admin, async, auth, citizen, express, globals, pgo, router, unverifiedUser, user, va;

async = require('async');

express = require('express');

router = express.Router();

auth = require('../user/authentication');

user = require('../user/user');

unverifiedUser = require('../user/unverifiedUser');

citizen = require('../user/citizen');

admin = require('../user/admin');

pgo = require('../user/pgo');

va = require('../user/va');

globals = require('../globals');

PGConnect = globals.PGConnect;

router.post('/signin', function(req, res, next) {
  var email;
  email = req.param('email');
  auth.verifyCredentials(email, req.param('password'), function(err, validity) {
    if (err) {
      return next(err);
    }
    if (validity !== true) {
      res.locals.error = new Error('Invalid Credentials');
      res.locals.error.details = "It looks like this was the result of either: <br /><ul><li>Non-existent user</li><li>a mistyped password</li></ul>";
      res.locals.autoFillUsingLocals = true;
      res.locals.email = email;
      return next();
    } else {
      user = {
        email: email
      };
      return async.map([admin, pgo, va, citizen], function(user, callback) {
        return user.getForEmail(email, callback);
      }, function(err, users) {
        var _i, _len;
        console.log(users);
        for (_i = 0, _len = users.length; _i < _len; _i++) {
          user = users[_i];
          if (user != null) {
            req.session.user = user;
          }
        }
        console.log(req.session.user);
        if (req.param('redirect')) {
          return res.redirect(req.param('redirect'));
        } else {
          return res.redirect('/dashboard/');
        }
      });
    }
  });
});

router.get('/login', function(req, res, next) {
  return res.redirect(req.url.replace(/^\/login/, "/signin"));
});

router.get('/signin', function(req, res, next) {
  if (req.session.user) {
    return res.redirect('/dashboard/');
  }
  next();
});

router.get('/logout', function(req, res, next) {
  return res.redirect(req.url.replace(/^\/logout/, "/signout"));
});

router.all('/signout', function(req, res, next) {
  if (!req.session.user) {
    return res.redirect('/');
  }
  req.session.user = null;
  res.redirect('/auth/signin');
});

router.get('/register', function(req, res, next) {
  return res.redirect(req.url.replace(/^\/login/, "/register"));
});

router.post('/signup', function(req, res, next) {
  var email, name;
  email = req.param('email');
  name = req.param('name');
  if (!/(\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,6})/.test(email)) {
    res.locals.error = new Error('Invalid email.');
    res.locals.autoFillUsingLocals = true;
    res.locals.name = name;
    res.locals.email = email;
    next();
    return;
  }
  unverifiedUser.addUnverifiedUser(email, name, function(err) {
    if (err) {
      res.locals.error = err;
      res.locals.autoFillUsingLocals = true;
      res.locals.name = name;
      res.locals.email = email;
      next();
      return;
    }
    res.locals.success = {
      msg: 'You have been sent a verification email. Please check your inbox and click verify to activate your account.'
    };
    return next();
  });
});

router.post('/verification', function(req, res, next) {
  var email, verificationKey;
  email = req.param('email');
  verificationKey = req.param('verificationKey');
  if (verificationKey in (verificationKey = '')) {
    res.locals.error = new Error('Invalid Verification Link');
    next();
    return;
  }
  return unverifiedUser.verifyVerificationKey(email, verificationKey, function(err, validity) {
    if (err) {
      res.locals.error = err;
      next();
      return;
    }
    if (validity === true) {
      if (req.param('redirect')) {
        return res.redirect(req.param('redirect'));
      } else {
        return res.redirect('/dashboard/');
      }
    } else {
      res.locals.error = new Error('Invalid Verification.');
      next();
    }
  });
});

router.all('/verification', function(req, res, next) {
  var verificationKey;
  verificationKey = req.param('verificationKey');
  if (verificationKey in (verificationKey = '')) {
    res.locals.error = new Error('Invalid Verification Link');
    next();
    return;
  }
  return unverifiedUser.getEmailForVerificationKey(verificationKey, function(err, email) {
    if (!email) {
      res.locals.error = new Error('Invalid Verification Link');
      next();
      return;
    }
    res.locals.email = email;
    res.locals.verificationKey = verificationKey;
    next();
  });
});

module.exports = router;
