// Generated by CoffeeScript 1.7.1
var async, express, pgo, router;

async = require('async');

express = require('express');

router = express.Router();

pgo = require('../user/pgo');

module.exports = router;
