// Generated by CoffeeScript 1.7.1
var admin, citizen, config, debug, express, globals, pgo, router, user, va;

express = require('express');

router = express.Router();

user = require('../user/user');

citizen = require('../user/citizen');

admin = require('../user/admin');

pgo = require('../user/pgo');

va = require('../user/va');

globals = require('../globals');

config = globals.config;

debug = globals.debug;

router.all(/^\/dashboard/, function(req, res, next) {
  if (!req.session.user) {
    return res.redirect("/auth/signin?redirect=" + (encodeURIComponent(req.url)));
  }
  switch (req.session.user.type) {
    case citizen.type:
      res.redirect(req.url.replace(/^\/dashboard/, "/user"));
      break;
    case va.type:
      res.redirect(req.url.replace(/^\/dashboard/, "/va"));
      break;
    case pgo.type:
      res.redirect(req.url.replace(/^\/dashboard/, "/pgo"));
      break;
    case admin.type:
      res.redirect(req.url.replace(/^\/dashboard/, "/admin"));
      break;
    case user.type:
      res.redirect(req.url.replace(/^\/dashboard/, "/citizen-registration"));
      break;
    default:
      res.redirect("/auth/signin?redirect=" + (encodeURIComponent(req.url)));
  }
});

router.all(/^\/admin/, admin.filter);

router.all(/^\/pgo/, pgo.filter);

router.all(/^\/va/, va.filter);

router.all(/^\/user/, citizen.filter);

router.all(/^\/citizen-registration/, function(req, res, next) {
  debug("Citizen Registration Auth Filter: " + req.url);
  if (!((req.session.user != null) && req.session.user.type === user.type)) {
    return res.redirect("/auth/signin?redirect=" + (encodeURIComponent(req.url)));
  }
  return next();
});

router.get('/login', function(req, res, next) {
  return res.redirect(req.url.replace(/^\/login/, "/auth/signin"));
});

router.get('/signin', function(req, res, next) {
  return res.redirect(req.url.replace(/^\/signin/, "/auth/signin"));
});

router.get('/logout', function(req, res, next) {
  return res.redirect(req.url.replace(/^\/logout/, "/auth/signout"));
});

router.get('/signout', function(req, res, next) {
  return res.redirect(req.url.replace(/^\/signout/, "/auth/signout"));
});

router.get('/register', function(req, res, next) {
  return res.redirect(req.url.replace(/^\/register/, "/auth/signup"));
});

router.get('/signup', function(req, res, next) {
  return res.redirect(req.url.replace(/^\/signup/, "/auth/signup"));
});

router.get('/_dismiss-warning', function(req, res, next) {
  req.session.dont_warn = true;
  if (req.param('redirect')) {
    return res.redirect(req.param('redirect'));
  } else {
    return res.redirect('/');
  }
});

module.exports = router;
