// Generated by CoffeeScript 1.7.1
var async, citizen, express, router;

async = require('async');

express = require('express');

router = express.Router();

citizen = require('../user/citizen');

module.exports = router;
