// Generated by CoffeeScript 1.7.1
var application, async, citizen, express, globals, router, va;

async = require('async');

express = require('express');

router = express.Router();

citizen = require('../user/citizen');

va = require('../user/va');

application = require('../passport/application');

globals = require('../globals');

router.all('/application/list', function(req, res, next) {
  va.getApplicationsWithProfileForVAWithEmail(req.session.user.email, function(err, applications) {
    var app, _i, _len;
    if (err) {
      return next(err);
    }
    for (_i = 0, _len = applications.length; _i < _len; _i++) {
      app = applications[_i];
      application.expandValueUsingMap(app);
      citizen.expandValueUsingMap(app);
    }
    res.locals.applications = applications;
    console.log(applications);
    next();
  });
});

module.exports = router;
