// Generated by CoffeeScript 1.7.1
var async, express, router, va;

async = require('async');

express = require('express');

router = express.Router();

va = require('../user/va');

module.exports = router;
